### ISSUE TITLE
What's the meaning of model/data/Vvalue*?

### ISSUE THREAD

**Issue by zzd1992** [LennyHuang15/Kddcup-Dispatching#1]
There are several json files named as `Vvalue*` in `model/data`.
Can you describe the format and the meaning of those files?

**Comment by lcy1996** [comment]
A list of expected future discouted sums of reward at each state. A state is defined as [s,t] where s is the grid index and t is the time slot index. Refer to "Large-Scale Order Dispatch in On-Demand Ride-Hailing
Platforms: A Learning and Planning Approach".

**Comment by zzd1992** [comment]
Thanks. 
Since all those files have the same format, what are the differences between them? And which one is suggested for this competition？I notice that `Vvalue_max_mov-grid-7` is used in the demo submission code.

**Comment by lcy1996** [comment]
Actually Vvalue_max_mov-grid-100.json and Vvalue_max_mov-grid-7 are the final versions, however both of them didn't give a good enough performance in the competition.
